[appendix]
= Jet Version Compatibility

The following rules currently apply for Jet for compile time
and runtime compatibility.

== Semantic Versioning

Hazelcast Jet uses https://semver.org/[Semantic Versioning] which
can be summarized as follows:

* MAJOR version when you make incompatible API changes,
* MINOR version when you add functionality in a backwards-compatible manner, and
* PATCH version when you make backwards-compatible bug fixes.

This means that a Jet job written using Pipeline API in a previous
minor version should compile in later minor versions.

However some exceptions apply:

* Classes in `com.hazelcast.jet.core` package which form the
<<expert-zone, Core API>> of Jet only provide PATCH level compatibility guarantee.
* Classes in `impl` packages do not provide any compatibility
guarantees between versions.

== Summary Table

The compatibility guarantees can be summarized as follows:

[%header]
|===
|Type|Component|Guarantee
|Compile Time|Job API|MINOR
|Compile Time|Pipeline API|MINOR
|Compile Time|Core API|PATCH
|Runtime|Member to Member|NONE
|Runtime|Management Center to Member|NONE
|Runtime|Client to Member|PATCH
|Runtime|Job State|PATCH
|Runtime|Command Line Tools|MINOR
|Runtime|Configuration XML files|PATCH
|Runtime|Metrics (JMX)|PATCH
|===

== Runtime Compatibility

=== Members

Jet requires that all members in a cluster use the same PATCH version.
When updating Jet to a newer PATCH version, the whole cluster must be
shutdown and restarted with the newer version at once.

=== Management Center

Management Center, like members, is only compatible with the same
PATCH version. This means that Management Center and the cluster
must have the exact same PATCH version to be compatible.

=== Clients

Jet clients are compatible with the members running on the same MINOR
version. This means that a client using an older or newer PATCH version
should be able to connect and work with a cluster that's running a different
PATCH version.

== Job State Compatibility

Job state is only compatible across the same MINOR version and only
backwards-compatible i.e. a newer PATCH version is be able to understand
the job state from a previous PATCH version.

This means that if you have a running job, using the Job Upgrade
and Lossless Cluster Restart features you are able to upgrade the cluster
to a newer PATCH version without losing the state of a running job.

== Command Line Tools and Configuration Files

The command line tools provided such as `jet` and the configuration
XML files are backwards-compatible between MINOR versions. This means
that when upgrading a cluster to a new minor version, the XML configuration
for the previous version can be used without any modification.

== Metrics

Jet currently provides metrics to Management Center and also through
other means such as JMX. The metrics names may change between MINOR
versions but not between PATCH versions.

[appendix]
[[system-properties]]
= System Properties

The table below lists the system properties supported by Jet. Jet also
supports the system properties defined by Hazelcast IMDG, please see the
System properties chapter in Hazelcast IMDG Reference Manual.

NOTE: When you want to reconfigure a system property, you need to
restart the members for which the property is modified.

[cols="2,1,1,6a"]
.System Properties
|===
|Property Name
| Default Value
| Type
| Description

|`jet.job.scan.period`
|5000
|long [milliseconds]
|Jet will periodically check for new jobs to start and perform cleanup
of unused resources. This property configures how often this check and
cleanup will be done. Value is in milliseconds.

|`jet.shutdownhook.enabled`
|true
|boolean
|Whether a JVM shutdown hook is registered to shutdown the node
gracefully when the process is terminated. The shutdown hook will
terminate all running jobs and then gracefully terminate the note, in a
way that is equivalent to calling JetInstance.shutdown().

|`jet.job.results.ttl.seconds`
|604800 (7 days)
|long [seconds]
|Maximum number of time in seconds the job results will be kept in the
cluster. They will be automatically deleted after this period is
reached.

|`jet.job.results.max.size`
|1000
|integer
|Maximum number of job results to keep in the cluster, the oldest
results will be automatically deleted after this size is reached.

|`jet.home`
|_Jet installation path_
|string
|Root of Jet installation. Used as default location for the Lossless
Cluster Restart store. By default it will be automatically set to the
start of the Jet installation path.

|`jet.idle.cooperative.min.microseconds`
|25
|long [microseconds]
|The minimum time in microseconds the cooperative worker threads will
sleep if none of the tasklets made any progress. Lower values increase
idle CPU usage but may result in decreased latency. Higher values will
increase latency and very high values (>10000µs) will also limit
throughput.

Note: the underlying `LockSupport.parkNanos(long)` call may actually
sleep longer depending on the operating system (up to 15000µs on
Windows). See the
https://hazelcast.com/blog/locksupport-parknanos-under-the-hood-and-the-curious-case-of-parking/[Hazelcast
blog post] about this subject  for more details.

|`jet.idle.cooperative.max.microseconds`
|500
|long [microseconds]
|The maximum time in microseconds the cooperative worker threads will
sleep if none of the tasklets made any progress. Lower values increase
idle CPU usage but may result in decreased latency. Higher values will
increase latency and very high values (>10000µs) will also limit
throughput.

Note: the underlying `LockSupport.parkNanos(long)` call may actually
sleep longer depending on the operating system (up to 15000µs on
Windows). See the
https://hazelcast.com/blog/locksupport-parknanos-under-the-hood-and-the-curious-case-of-parking/[Hazelcast
blog post] about this subject  for more details.

|`jet.idle.noncooperative.min.microseconds`
|25
|long [microseconds]
|The minimum time in microseconds the non-cooperative worker threads
will sleep if none of the tasklets made any progress. Lower values
increase idle CPU usage but may result in decreased latency. Higher
values will increase latency and very high values (>10000µs) will also
limit throughput.

Note: the underlying `LockSupport.parkNanos(long)` call may actually
sleep longer depending on the operating system (up to 15000µs on
Windows). See the
https://hazelcast.com/blog/locksupport-parknanos-under-the-hood-and-the-curious-case-of-parking/[Hazelcast
blog post] about this subject  for more details.

|`jet.idle.noncooperative.max.microseconds`
|5000
|long [microseconds]
|The maximum time in microseconds the non-cooperative worker threads
will sleep if none of the tasklets made any progress. Lower values
increase idle CPU usage but may result in decreased latency. Higher
values will increase latency and very high values (>10000µs) will also
limit throughput.

Note: the underlying `LockSupport.parkNanos(long)` call may actually
sleep longer depending on the operating system (up to 15000µs on
Windows). See the
https://hazelcast.com/blog/locksupport-parknanos-under-the-hood-and-the-curious-case-of-parking/[Hazelcast
blog post] about this subject  for more details.

|===


[appendix]
= Common Exceptions

You may see the following exceptions thrown when working with Jet:

* {jet-javadoc}/JetException.html[`JetException`]:
A general exception thrown if a job failure occurs. It has the original
exception as its cause.
* {jet-javadoc}/core/TopologyChangedException.html[`TopologyChangedException`]:
Thrown when a member participating in a job leaves the cluster. If
auto-restart is enabled, Jet will restart the job automatically, without
throwing the exception to the user.
* {jet-javadoc}/core/JobNotFoundException.html[`JobNotFoundException`]:
Thrown when the coordinator node is not able to find the metadata for a
given job.

There are also several Hazelcast exceptions that might be thrown when
interacting with `JetInstance`. For a description of Hazelcast IMDG
exceptions, please refer to the
{hz-refman}#common-exception-types[IMDG Reference manual].

[appendix]
[[phone-homes]]
= Phone Homes

Hazelcast uses phone home data to learn about the usage of Hazelcast Jet.

Hazelcast Jet instances call our phone home server initially when they
are started and then every 24 hours. This applies to all the instances
joined to the cluster.

== What is sent in?

The following information is sent in a phone home:

* Hazelcast Jet version
* Local Hazelcast Jet member UUID
* Download ID
* A hash value of the cluster ID
* Cluster size bands for 5, 10, 20, 40, 60, 100, 150, 300, 600 and > 600
* Number of connected clients bands of 5, 10, 20, 40, 60, 100, 150, 300, 600 and > 600
* Cluster uptime
* Member uptime
* Environment Information:
** Name of operating system
** Kernel architecture (32-bit or 64-bit)
** Version of operating system
** Version of installed Java
** Name of Java Virtual Machine
* Hazelcast IMDG Enterprise specific:
** Number of clients by language (Java, C++, C#)
** Flag for Hazelcast Enterprise
** Hash value of license key
** Native memory usage

== Phone Home Code

The phone home code itself is open source. Please see https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/internal/util/PhoneHome.java[here].

== Disabling Phone Homes

Set the `hazelcast.phone.home.enabled` system property to false either
in the config or on the Java command line.

Starting with Hazelcast Jet 0.5, you can also disable the phone home
using the environment variable `HZ_PHONE_HOME_ENABLED`. Simply add the
following line to your `.bash_profile`:

----
export HZ_PHONE_HOME_ENABLED=false
----

== Phone Home URL

The URL used for phone home requests is

----
http://phonehome.hazelcast.com/ping
----

[appendix]
= Migration Guides

This appendix provides guidelines for upgrading to a new Hazelcast Jet
version. See also the
link:https://docs.hazelcast.org/docs/jet/release-notes/index.html[Release Notes]
document for the changes for each Hazelcast Jet release.

== Upgrading to Hazelcast Jet 4.0

Jet 4.0 is a major version release. Major releases allow us to break
compatibility in the API, as well as to remove previously deprecated
parts of the API.

=== Jet on IMDG 4.0

Jet 4.0 uses IMDG 4.0, which is also a major release with its own
breaking changes. For details see
link:https://docs.hazelcast.org/docs/rn/index.html[IMDG Release Notes]
and
link:https://docs.hazelcast.org/docs/latest/manual/html-single/#migration-guides[IMDG Migration Guides].

The most important changes that have affected Jet are as follows:

* Many packages have been renamed, or classes moved from one package to
another and these changes have been followed in Jet. For details see
link:https://docs.hazelcast.org/docs/rn/index.html#4-0[IMDG Release Notes].
The change most obvious in Jet is that many classes have been moved from
the generic `com.hazelcast.core` package to more specific packages, like
`com.hazelcast.map` or `com.hazelcast.collection`.

* Serializable variants of `java.util.function` interfaces have been
moved from Jet (`com.hazelcast.jet.function` package) to IMDG
(`com.hazelcast.function` package): `BiConsumerEx`,`BiFunctionEx`,
`BinaryOperatorEx`, `BiPredicateEx`,`ComparatorEx`, `ComparatorsEx`,
`ConsumerEx`, `FunctionEx`,`Functions`, `PredicateEx`, `SupplierEx`,
`ToDoubleFunctionEx`, `ToIntFunctionEx`, `ToLongFunctionEx`.

* Generic parameters on several methods and classes have been updated/fixed
(i.e. `EntryProcessor`) (see
link:https://docs.hazelcast.org/docs/latest/manual/html-single/#introducing-lambda-friendly-interfaces[relevant section]
in IMDG Migration Guide). These changes have been adopted in Jet.

* "Group name" config option is now called "cluster name". See next code
snippet. These changes have been adapted to the Jet Command Line too
(`-g/--groupName` replaced by `-n/--cluster-name` option).
+
[source]
----
include::{javasource}/migration/Migration.java[tag=config1]
----

* `EventJournalConfig` has been moved from top level `Config` class to
data-structure specific configs (`MapConfig`,`CacheConfig`).
+
[source]
----
include::{javasource}/migration/Migration.java[tag=config2]
----

* Async methods in IMDG return `CompletionStage` now rather than the old
`ICompletableFuture` (see
link:https://docs.hazelcast.org/docs/latest/manual/html-single/#removal-of-icompletablefuture[relevant section]
in IMDG Migration Guide) and these have been adopted in Jet.

=== Jet API Changes
Jet 4.0 makes multiple breaking changes in its own APIs:

* `IMapJet`, `ICacheJet` and `IListJet` interfaces have been removed and
have been replaced with IMDG's `IMap`, `ICache` and `IList`.

* `Pipeline.drawFrom` has been renamed to `Pipeline.readFrom` and
`GeneralStage.drainTo` has been renamed to `GeneralStage.writeTo`.
+
[source]
----
include::{javasource}/migration/Migration.java[tag=pipeline1]
----

* ``ContextFactory`` has been renamed to `ServiceFactory` and support for
instance-wide initialization has been added to it. It takes
`ProcessorSupplier.Context` instead of just `JetInstance` and the
convenience methods from `ServiceFactories` should be used for
initialization.
+
[source]
----
include::{javasource}/migration/Migration.java[tag=serviceFactory1]
----

* `map/filter/flatMapUsingContext` has been renamed to
`map/filter/flatMapUsingService`.
+
[source]
----
include::{javasource}/migration/Migration.java[tag=pipeline2]
----

* `withMaxPendingCallsPerProcessor(int)` and
`withUnorderedAsyncResponses()` methods have been removed from
`ServiceFactory`. They have been properties relevant in the context of
asynchronous operations, so have been used in conjunction with
`GeneralStage.mapUsingServiceAsync(...)` calls. In Jet 4.0 the
`GeneralStage.mapUsingServiceAsync(...)` method has a new variant with
explicit parameters for the above settings.
+
[source]
----
include::{javasource}/migration/Migration.java[tag=serviceFactory2]
----

* Signature of `com.hazelcast.jet.pipeline.Sinks#mapWithEntryProcessor`
method has changed, in order to reflect the way in which `EntryProcessor`
has been made more lambda-friendly in IMDG (see
link:https://docs.hazelcast.org/docs/latest/manual/html-single/#introducing-lambda-friendly-interfaces[relevant section]
in IMDG Migration Guide). The return type of the `EntryProcessor` is now
an explicit parameter in ``mapWithEntryProcessor``'s method signature.
+
[source]
----
include::{javasource}/migration/Migration.java[tag=entryProcessor1]
----

* HDFS source and sink have been renamed to `Hadoop.inputFormat` and
 `Hadoop.outputFormat`.

* `MetricsConfig` is no longer part of `JetConfig`, but resides in the
IMDG `Config` class.
+
[source]
----
include::{javasource}/migration/Migration.java[tag=config3]
----

* Generic wildcard parameters in `Traverser` class have been tweaked
slightly. Change shouldn't affect anything in
practice.

* Lambdas have been moved to become last parameter, where applicable,
for sources and sinks.

* `JetBootstrap.getInstance()` has been moved to
`Jet.bootstrappedInstance()` which automatically creates an isolated
instance when not running through `jet submit`. If used from
`jet submit`, the behaviour remains as it has been.

* `JobConfig.addResource(...)` methods have been renamed to
`addClasspathResource(...)`.

* `ResourceType.REGULAR_FILE` has been renamed to `ResourceType.FILE`,
but at the same time `ResourceType`,`ResourceConfig` and
`JobConfig.getResourceConfigs()` have become private API, so we
discourage their usage as much as possible.

[appendix]
= FAQ

You can refer to the https://jet.hazelcast.org/faq/[FAQ] page to see the
answers to frequently asked questions related to topics such as the
relationship and differences between Hazelcast Jet and Hazelcast IMDG,
Jet's APIs and roadmap.

[appendix]
= License Questions

Hazelcast Jet is distributed using the
http://www.apache.org/licenses/LICENSE-2.0[Apache License 2],
therefore permissions are granted to use, reproduce and distribute it
along with any kind of open source and closed source applications.

Depending on the used feature-set, Hazelcast Jet has certain runtime
dependencies which might have different licenses. Following are
dependencies and their respective licenses.

== Embedded Dependencies

Embedded dependencies are merged (shaded) with the Hazelcast Jet
codebase at compile-time. These dependencies become an integral part of
the Hazelcast Jet distribution.

For license files of embedded dependencies, please see the `license`
directory of the Hazelcast Jet distribution, available at our
https://jet.hazelcast.org/download/[download page].

=== minimal-json

minimal-json is a JSON parsing and generation library which is a part of
the Hazelcast Jet distribution. It is used for communication
between the Hazelcast Jet cluster and the Management Center.

minimal-json is distributed under the
http://opensource.org/licenses/MIT[MIT license] and offers the same
rights to add, use, modify, and distribute the source code as the Apache
License 2.0 that Hazelcast uses. However, some other restrictions might
apply.

=== picocli

picocli is a command line parser which is used for the implementation of
`jet` command line tool.

picocli is distributed under the terms of the
http://www.apache.org/licenses/LICENSE-2.0[Apache License 2].

=== Runtime Dependencies

Depending on the used features, additional dependencies might be added
to the dependency set. Those runtime dependencies might have other
licenses. See the following list of additional runtime dependencies.

=== Apache Hadoop

Hazelcast integrates with Apache Hadoop and can use it as a data
 sink or source. Jet has a dependency on the libraries required to
 read from and write to the Hadoop File System.

Apache Hadoop is distributed under the terms of the
http://www.apache.org/licenses/LICENSE-2.0[Apache License 2].

=== Apache Kafka

Hazelcast integrates with Apache Kafka and can make use of it as a
data sink or source. Hazelcast has a dependency on Kafka client
libraries.

Apache Kafka is distributed under the terms of the
http://www.apache.org/licenses/LICENSE-2.0[Apache License 2].

=== Spring

Hazelcast integrates with Spring and can be configured using Spring
Context. Jet has a dependency on the libraries required to create a
Spring context.

Spring is distributed under the terms of the
http://www.apache.org/licenses/LICENSE-2.0[Apache License 2].

