hazelcast-client:
  # Name of the cluster to connect to. Must match what's configured on the nodes
  cluster-name: jet
  network:
    # List of addresses for the client to try to connect to
    cluster-members:
      - 127.0.0.1
    connection-timeout: 60000